### PR TITLE
user profile, follow or unfollow

### PR DESCRIPTION
**Pull request by git-0r**
## Features
 - Follow/Unfollow a user
 - User profile
 - Edit bio, url, profile picture
 
---

socialfollow

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
good naming convention and components are modular .

**Comment by srinibas39** [comment]
Hey Rohit UI looks good.
Just one suggestion
1.I can add blank space as a playlist name.You can add a check on that

**Review by shobit1337 — APPROVED** [review]
UI looks good👍
code is also good readable,

**Comment by srinibas39** [comment]
Hey UI Looks good,
Only 1 suggestion,
1.I can add a blank space as a post. you can add a check on that
Capture

**Pull request merged**
